# Generated by Django 6.0.6 on 2026-07-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_remove_question_reponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
