# Generated by Django 6.0.6 on 2026-07-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_quiz_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='reponse',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
