# Generated by Django 6.0.6 on 2026-07-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_choice_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='choice',
            name='reponse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
