# Generated by Django 6.0.6 on 2026-07-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_question_number_alter_choice_reponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
