# Generated by Django 6.0.6 on 2026-07-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='choice',
            field=models.CharField(blank=True, choices=[('RGPD', 'rgpd'), ('L25', 'Loi 25'), ('BOTH', 'both')], default=None, null=True),
        ),
    ]
